### PR TITLE
Fix memory leaks

### PR DESCRIPTION
**Pull request by davhdavh**
The various elements are not cleaned up after using

### CODE REVIEW

**Comment by billpull** [comment]
Looks like this introduced some JSHint errors. The code looks good to me so if you can fix the linting
I will merge it.

**Comment by davhdavh** [comment]
I cant seem to extract the jshint log from Travis, can you send me the warnings?

**Comment by billpull** [comment]
I think this is the only problem
```
153	Expected an assignment or function call and instead saw an expression.
```
oddly enough I cant seem to find the output in travis either I had to run locally

**Comment by davhdavh** [comment]
Done

**Pull request merged**
